m1 = [
  "0x00", "0x00", "0x00", "0x00",
  "0x00", "0x00", "0x00", "0x00",
  "0x00", "0x00", "0x00", "0x00",
  "0x00", "0x00", "0x00", "0x00",
  "0x00", "0x00", "0x00", "0x00",
  "0x00", "0x00", "0x00", "0x00",
  "0x00", "0x00", "0x00", "0x00",
  "0x00", "0x00", "0x00", "0x00",
]

m2 = [
  "0x01", "0x01", "0x01", "0x01",
  "0x01", "0x01", "0x01", "0x01",
  "0x01", "0x01", "0x01", "0x01",
  "0x01", "0x01", "0x01", "0x01",
  "0x01", "0x01", "0x01", "0x01",
  "0x01", "0x01", "0x01", "0x01",
  "0x01", "0x01", "0x01", "0x01",
  "0x01", "0x01", "0x01", "0x01",
]
